### ISSUE TITLE
Crashing Servers

### ISSUE THREAD

**Issue by lgnmcrules** [ValhelsiaTeam/Valhelsia-Structures#3]
This message is spammed hundreds of times before a server crashes:
[Server thread/ERROR] [net.minecraft.world.gen.feature.structure.Structures/]: Unknown structure piece id: valhelsia_structures:small_dungeon

I assume it's an unknown structure piece id.  This occurs in the ocean.

**Comment by sdaddy** [comment]
Is there any update on this? I'm getting the same error and crash, but I want to make sure I have the right culprit. Thank you.

**Comment by Vaelzan** [comment]
I think I may have fixed it for the 1.14.4 version, and it should be fixed in the next 1.15.2 version as well when that gets released.

**Comment by sebastianfast** [comment]
I'm also getting that error message. For me, the server stops working as soon as the server tries to load the structure. I'm using v15.0.2
