### ISSUE TITLE
Config blacklist

### ISSUE THREAD

**Issue by Sunekaer** [ValhelsiaTeam/Valhelsia-Structures#4]
Structures are spawning in dims like https://www.curseforge.com/minecraft/mc-mods/just-another-void-dimension
Would it be possible that you could add a common config with a blacklist for biomes or dimensions where the structures cant spawn?

**Comment by Khytwel** [comment]
Yes this will be done for the next update of the mod.

**Comment by TheLastNoddy** [comment]
Just to piggy back off this idea, would also be great to be able to turn down the spawn rates of structures within config. Currently if the right spawn conditions are met (e.g. Plains biome) the structures can spawn all over the place.

**Comment by Vaelzan** [comment]
The new version has a check to only generate structures in the overworld. Later this will be configurable but for now it's set to always be overworld only.

There are also config options for rarity of structures, as well as spacing and disabling individual structures entirely if you wish.
