### ISSUE TITLE
Issue with resource

### ISSUE THREAD

**Issue by RickyGeo** [ValhelsiaTeam/Valhelsia-Structures#52]
its hard use digital Mining to farm a loot of uranium ( add other mod for this or add other dimension for mining and other quarry thing)
and also Emerald its to rarely and digital Mining cant mining it....

**Comment by Vaelzan** [comment]
I think you're in the wrong place. This is the issue tracker for the Valhelsia Structures mod, not the Valhelsia mod packs.
