### ISSUE TITLE
Terrain mask for the surrounding environment of an overworld structure

### ISSUE THREAD

**Issue by ampacs** [ValhelsiaTeam/Valhelsia-Structures#6]
Structures seem to spawn without much regard for their surrounding environment right now. This can sometimes lead to awkward placements, like in this case:

![2020-04-22_22 20 10](https://user-images.githubusercontent.com/9452595/80035778-7ea14a00-84e8-11ea-946e-93dd10b8cbbe.png)
![2020-04-22_22 28 26](https://user-images.githubusercontent.com/9452595/80035826-98db2800-84e8-11ea-819c-65865a768321.png)

May I suggest applying a mask to the surrounding terrain? I imagine it's not trivial, as you would need to affect the world generation, but I would like you to consider adding such a feature in the future.

**Comment by Khytwel** [comment]
Hey, 
We plan to improve all this in the next mod updates.

**Comment by 630Studios** [comment]
I actually like this a little bit. Overhangs do not happen enough in the game, and even less often with something interesting on them.

Maybe a configuration option to allow it? I can see why others might not like it, it does not look "natural", but me personally I am all for interesting and fun at this point.

Great mod btw. It with a few other mods has given the game new life for me.

**Comment by Vaelzan** [comment]
We have improved this somewhat in the latest update, where the positioning of structures has been improved substantially. It isn't perfect though, so we will be potentially adding a method to generate new terrain below the structures as well - similarly to how some vanilla village structures place cobblestone beneath them (but hopefully better integrated and nicer looking than vanilla).

**Comment by winnetrie83** [comment]
well to be honest, that's the first time i see this. all previous structeres i encountered were almost perfectly integrated in the terrain

**Comment by Khytwel** [comment]
Fixed in the last update for version 1.16.1. This will also be ported for old versions.
