### ISSUE TITLE
[1.15.2] Structures overwrite village buildings

### ISSUE THREAD

**Issue by TheLastNoddy** [ValhelsiaTeam/Valhelsia-Structures#8]
Minecraft: 1.15.2
Forge Version: 31.1.61
Valhelsia Structures: valhelsia_structures-15.0.2a

It looks like Valhelsia structures can spawn over the top of pre-existing structures such as villages.

![Valhelsia](https://user-images.githubusercontent.com/46658656/80544815-c3762680-89a9-11ea-937d-648a885a6a55.PNG)

**Comment by Vaelzan** [comment]
Fixed in 15.0.3 and 14.0.4 - specifically, no surface structure can now spawn within five chunks of a village.

**Comment by Vaelzan** [comment]
Also, thank you for the report and screenshot. :)
