### ISSUE TITLE
Towns / City addition

### ISSUE THREAD

**Issue by disastercube** [ValhelsiaTeam/Valhelsia-Structures#9]
This mod has a unique vanilla vibe which could be great if it would add bigger populated structure types such as town or cities with villagers. It would ad a unique touch that almost no mod ads and would make the vanilla experience much more thrilling. Towns would be bigger then normal villages and overall houses could be made with the same medieval / vanilla style this mod already has.
It could also added different town types that would differ from biomes. Maybe even flags across the towns that would represent the colony or union. There might be even walls which might help defending the town from a pillager raid. Talking about them, pillagers didn't get much love. Making them a camp or secret hideouts would make a fight against them or a simple "misstep" in their territory much more terrifying.  (town houses could consist with workstations for villager professions)

Besides TekTopia that adds populated areas, mods that add population with vanilla vibe are non existent. Not only this could benefit the mod by making it much more popular but would enhance the game in a way no other mod has succeeded yet. Just Imagine combining this mod with TerraForged and stumping across a place like this with a living town:

![2020-05-21_14 49 40](https://user-images.githubusercontent.com/62697421/82560764-569e1880-9b72-11ea-8c42-603488a32e1b.png)

**Comment by Khytwel** [comment]
Thank you for your feedback! We still have a lot to do but we will take your suggestion into account.
But come on our Discord server if you want talk about the mod :)

https://discord.com/invite/reQZEXu
